# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wuwen/program/CabanaPD

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wuwen/program/CabanaPD

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wuwen/program/CabanaPD/CMakeFiles /home/wuwen/program/CabanaPD//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wuwen/program/CabanaPD/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ElasticWave

# Build rule for target.
ElasticWave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ElasticWave
.PHONY : ElasticWave

# fast build rule for target.
ElasticWave/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/ElasticWave.dir/build.make examples/mechanics/CMakeFiles/ElasticWave.dir/build
.PHONY : ElasticWave/fast

#=============================================================================
# Target rules for targets named KalthoffWinkler

# Build rule for target.
KalthoffWinkler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KalthoffWinkler
.PHONY : KalthoffWinkler

# fast build rule for target.
KalthoffWinkler/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/KalthoffWinkler.dir/build.make examples/mechanics/CMakeFiles/KalthoffWinkler.dir/build
.PHONY : KalthoffWinkler/fast

#=============================================================================
# Target rules for targets named CrackBranching

# Build rule for target.
CrackBranching: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CrackBranching
.PHONY : CrackBranching

# fast build rule for target.
CrackBranching/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/CrackBranching.dir/build.make examples/mechanics/CMakeFiles/CrackBranching.dir/build
.PHONY : CrackBranching/fast

#=============================================================================
# Target rules for targets named FragmentingCylinder

# Build rule for target.
FragmentingCylinder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FragmentingCylinder
.PHONY : FragmentingCylinder

# fast build rule for target.
FragmentingCylinder/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/FragmentingCylinder.dir/build.make examples/mechanics/CMakeFiles/FragmentingCylinder.dir/build
.PHONY : FragmentingCylinder/fast

#=============================================================================
# Target rules for targets named RandomCracks

# Build rule for target.
RandomCracks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RandomCracks
.PHONY : RandomCracks

# fast build rule for target.
RandomCracks/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/RandomCracks.dir/build.make examples/mechanics/CMakeFiles/RandomCracks.dir/build
.PHONY : RandomCracks/fast

#=============================================================================
# Target rules for targets named DogboneTensileTest

# Build rule for target.
DogboneTensileTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DogboneTensileTest
.PHONY : DogboneTensileTest

# fast build rule for target.
DogboneTensileTest/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/DogboneTensileTest.dir/build.make examples/mechanics/CMakeFiles/DogboneTensileTest.dir/build
.PHONY : DogboneTensileTest/fast

#=============================================================================
# Target rules for targets named PlateWithHole

# Build rule for target.
PlateWithHole: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PlateWithHole
.PHONY : PlateWithHole

# fast build rule for target.
PlateWithHole/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/PlateWithHole.dir/build.make examples/mechanics/CMakeFiles/PlateWithHole.dir/build
.PHONY : PlateWithHole/fast

#=============================================================================
# Target rules for targets named ColdSprayImpact

# Build rule for target.
ColdSprayImpact: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ColdSprayImpact
.PHONY : ColdSprayImpact

# fast build rule for target.
ColdSprayImpact/fast:
	$(MAKE) $(MAKESILENT) -f examples/mechanics/CMakeFiles/ColdSprayImpact.dir/build.make examples/mechanics/CMakeFiles/ColdSprayImpact.dir/build
.PHONY : ColdSprayImpact/fast

#=============================================================================
# Target rules for targets named ThermalDeformation

# Build rule for target.
ThermalDeformation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThermalDeformation
.PHONY : ThermalDeformation

# fast build rule for target.
ThermalDeformation/fast:
	$(MAKE) $(MAKESILENT) -f examples/thermomechanics/CMakeFiles/ThermalDeformation.dir/build.make examples/thermomechanics/CMakeFiles/ThermalDeformation.dir/build
.PHONY : ThermalDeformation/fast

#=============================================================================
# Target rules for targets named ThermalCrack

# Build rule for target.
ThermalCrack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThermalCrack
.PHONY : ThermalCrack

# fast build rule for target.
ThermalCrack/fast:
	$(MAKE) $(MAKESILENT) -f examples/thermomechanics/CMakeFiles/ThermalCrack.dir/build.make examples/thermomechanics/CMakeFiles/ThermalCrack.dir/build
.PHONY : ThermalCrack/fast

#=============================================================================
# Target rules for targets named ThermalDeformationHeatTransfer

# Build rule for target.
ThermalDeformationHeatTransfer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThermalDeformationHeatTransfer
.PHONY : ThermalDeformationHeatTransfer

# fast build rule for target.
ThermalDeformationHeatTransfer/fast:
	$(MAKE) $(MAKESILENT) -f examples/thermomechanics/CMakeFiles/ThermalDeformationHeatTransfer.dir/build.make examples/thermomechanics/CMakeFiles/ThermalDeformationHeatTransfer.dir/build
.PHONY : ThermalDeformationHeatTransfer/fast

#=============================================================================
# Target rules for targets named ThermalDeformationHeatTransferPrenotched

# Build rule for target.
ThermalDeformationHeatTransferPrenotched: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThermalDeformationHeatTransferPrenotched
.PHONY : ThermalDeformationHeatTransferPrenotched

# fast build rule for target.
ThermalDeformationHeatTransferPrenotched/fast:
	$(MAKE) $(MAKESILENT) -f examples/thermomechanics/CMakeFiles/ThermalDeformationHeatTransferPrenotched.dir/build.make examples/thermomechanics/CMakeFiles/ThermalDeformationHeatTransferPrenotched.dir/build
.PHONY : ThermalDeformationHeatTransferPrenotched/fast

#=============================================================================
# Target rules for targets named PowderFill

# Build rule for target.
PowderFill: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PowderFill
.PHONY : PowderFill

# fast build rule for target.
PowderFill/fast:
	$(MAKE) $(MAKESILENT) -f examples/dem/CMakeFiles/PowderFill.dir/build.make examples/dem/CMakeFiles/PowderFill.dir/build
.PHONY : PowderFill/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ColdSprayImpact"
	@echo "... CrackBranching"
	@echo "... DogboneTensileTest"
	@echo "... ElasticWave"
	@echo "... FragmentingCylinder"
	@echo "... KalthoffWinkler"
	@echo "... PlateWithHole"
	@echo "... PowderFill"
	@echo "... RandomCracks"
	@echo "... ThermalCrack"
	@echo "... ThermalDeformation"
	@echo "... ThermalDeformationHeatTransfer"
	@echo "... ThermalDeformationHeatTransferPrenotched"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

