/****************************************************************************
 * Copyright (c) 2024 by Oak Ridge National Laboratory                      *
 * All rights reserved.                                                     *
 *                                                                          *
 * This file is part of CabanaPD. CabanaPD is distributed under a           *
 * BSD 3-clause license. For the licensing terms see the LICENSE file in    *
 * the top-level directory.                                                 *
 *                                                                          *
 * SPDX-License-Identifier: BSD-3-Clause                                    *
 ****************************************************************************/
//this is generated by chatgpt

#ifndef FORCE_MODELS_PMB_JOHNSONCOOK_H
#define FORCE_MODELS_PMB_JOHNSONCOOK_H

#include <Kokkos_Core.hpp>

#include <CabanaPD_Constants.hpp>
#include <CabanaPD_ForceModels.hpp>
#include <CabanaPD_Types.hpp>
#include <force_models/CabanaPD_PMB.hpp>

namespace CabanaPD
{

// Johnson-Cook mechanics tag (kept local to this header by request).
struct JohnsonCook
{
};

// Johnson-Cook plasticity for PMB (bond-based).
//
// JC: sigma_y = (A + B * eps_p^n) * (1 + C * ln(eps_dot/eps_dot0))
//              * (1 - T*^m), T* = (T - T0) / (Tm - T0)
//
// PD mapping (framework):
// - plastic strain: eps_p ~ |s_p|
// - rate: eps_dot ~ |s_p - s_prev| / dt
// - yield stretch: s_y = sigma_y / (3K)
// - elastic stretch: s_eff = s - s_p
//
// This is a framework: temperature and rate definitions can be refined.
template <class MemorySpace>
struct BaseForceModelPMB<JohnsonCook, MemorySpace>
    : public BaseForceModelPMB<Elastic>, public BasePlasticity<MemorySpace>
{
    using base_type = BaseForceModelPMB<Elastic>;
    using base_plasticity_type = BasePlasticity<MemorySpace>;
    using mechanics_type = JohnsonCook;

    using base_type::K;
    using base_type::c;
    using base_type::delta;
    using base_plasticity_type::_s_p;
    using neighbor_view_type = typename base_plasticity_type::NeighborView;

    // Johnson-Cook parameters.
    double A;
    double B;
    double n;
    double C;
    double eps_dot0;
    double m;
    double T0;
    double Tm;
    double _dt;

    // Previous plastic stretch for rate estimate (framework only).
    neighbor_view_type _s_prev;

    BaseForceModelPMB( PMB model, mechanics_type, MemorySpace,
                       const double _delta, const double _K, const double _A,
                       const double _B, const double _n, const double _C,
                       const double _eps_dot0, const double _m, const double _T0,
                       const double _Tm, const double dt )
        : base_type( model, NoFracture{}, _delta, _K )
        , base_plasticity_type()
        , A( _A )
        , B( _B )
        , n( _n )
        , C( _C )
        , eps_dot0( _eps_dot0 )
        , m( _m )
        , T0( _T0 )
        , Tm( _Tm )
        , _dt( dt )
    {
    }

    void updateBonds( const int num_local, const int max_neighbors )
    {
        base_plasticity_type::updateBonds( num_local, max_neighbors );
        Kokkos::realloc( _s_prev, num_local, max_neighbors );
        Kokkos::deep_copy( _s_prev, 0.0 );
    }

    KOKKOS_INLINE_FUNCTION
    double normalizedTemperature( const double T ) const
    {
        const double denom = ( Tm - T0 );
        if ( denom <= 0.0 )
            return 0.0;
        double t = ( T - T0 ) / denom;
        if ( t < 0.0 )
            t = 0.0;
        if ( t > 1.0 )
            t = 1.0;
        return t;
    }

    KOKKOS_INLINE_FUNCTION
    double jcYieldStress( const double eps_p, const double eps_p_dot,
                          const double T ) const
    {
        const double rate = eps_p_dot > 0.0 ? eps_p_dot : eps_dot0;
        const double term1 = A + B * Kokkos::pow( eps_p, n );
        const double term2 = 1.0 + C * Kokkos::log( rate / eps_dot0 );
        const double tstar = normalizedTemperature( T );
        const double term3 = 1.0 - Kokkos::pow( tstar, m );
        return term1 * term2 * term3;
    }

    KOKKOS_INLINE_FUNCTION
    auto operator()( ForceCoeffTag, const int i, const int, const double s,
                     const double vol, const int n ) const
    {
        // Approximate plastic strain + rate from plastic stretch.
        const double s_p = _s_p( i, n );
        const double eps_p = Kokkos::abs( s_p );
        const double s_prev = _s_prev( i, n );
        const double eps_p_dot =
            Kokkos::abs( s_p - s_prev ) / ( _dt > 0.0 ? _dt : 1.0 );

        // TODO: wire temperature field for T.
        const double T = T0;

        const double sigma_y = jcYieldStress( eps_p, eps_p_dot, T );
        const double s_y = sigma_y / ( 3.0 * K );

        double s_eff = s - s_p;
        if ( s_eff >= s_y )
            _s_p( i, n ) = s - s_y;
        else if ( s_eff <= -s_y )
            _s_p( i, n ) = s + s_y;

        _s_prev( i, n ) = _s_p( i, n );

        s_eff = s - _s_p( i, n );
        return c * s_eff * vol;
    }

    KOKKOS_INLINE_FUNCTION
    auto operator()( EnergyTag, const int i, const int, const double s,
                     const double xi, const double vol, const int n ) const
    {
        // Placeholder elastic energy; refine for JC plasticity.
        const double s_eff = s - _s_p( i, n );
        return 0.25 * c * s_eff * s_eff * xi * vol;
    }
};

// Base PMB + Johnson-Cook, no fracture/temperature.
template <typename MemorySpace>
struct ForceModel<PMB, JohnsonCook, NoFracture, TemperatureIndependent,
                  MemorySpace>
    : public BaseForceModelPMB<JohnsonCook, MemorySpace>,
      BaseNoFractureModel,
      BaseTemperatureModel<TemperatureIndependent>
{
    using base_type = BaseForceModelPMB<JohnsonCook, MemorySpace>;
    using base_fracture_type = BaseNoFractureModel;
    using base_temperature_type = BaseTemperatureModel<TemperatureIndependent>;


    using base_type::operator();
    using base_fracture_type::operator();
    using base_temperature_type::operator();
    using base_type::updateBonds;
    using base_type::base_type;
};

// TODO: add fracture + temperature-dependent variants, and wire temperature.

} // namespace CabanaPD

#endif
